### ISSUE TITLE
Good practice when copying code

### ISSUE THREAD

**Issue by mikaelpatel** [sehlstrom/ElFi#1]
@sehlstrom 

I looked at this project to get a feeling for your work. I see that you have copied very large sections of code from Cosa example sketches without acknowledging this. I consider this very bad practice especially when it is obvious that you have pasted together a number of the Cosa example sketches. The worst is maybe the WebServer.h where you have copies a section of a sketch and copyrighted that. 

Other than that I believe you have good programming style and have grasped many of the concepts in Cosa even if you seem to be somewhat of a cut-and-paste programmer :)

Cheers!

**Comment by sehlstrom** [comment]
@mikaelpatel 
I am glad you had a look and I see what you mean with the acknowledgments and with the copyright violation of the WebServer.h file.

I do not count my self as a cut-and-paste programmer. But I do have to admit I am new to Arduino and the C++ language limiting my ability to understand all of the magic going on in sophisticated libraries such as Cosa et al. I am used to less complex object oriented java projects where it is more obvious on how to use the packages. The backside being rather clumsy memory handling.

Having that said, there are no excuses for not acknowledging someone else's work or violating copyrights. Please guide me of how to do this in order to do it in good practice and I will fixit ASAP.

**Comment by mikaelpatel** [comment]
@sehlstrom 
I recommend that one follows the same guidelines as for a research report. Copying code is just like a quotation and needs a reference. Also if you read the license text you should always include the copyrights of other authors when modifying the source. If you look closely at the Cosa source you will find a number of levels of acknowledgements. For instance, the VWI library is an OOP refactoring of VirtualWire, therefore the original copyright is still in place even though I have rewritten the whole library and extended it with multiple coders. 

As a rule I would recommend adding more references and acknowledgements in open-source. This strengthens your contribution and shows the we are all working together.

If you copy code segments from different part so simply maintain any copyright/license notice and give the source. If you have modified the code simply just acknowledge the source. This also goes for ideas, etc. See the list of acknowledgements in Canvas. 

A nice example is the notice in the Rotary Encoder. It is only a few lines of code but here I really want to acknowledge the great work done by the author to come up with such an elegant solution.

**Comment by sehlstrom** [comment]
@mikaelpatel 
Thanks! I have not contributed to the open-source domain before.

I hava added copyright for the WebServer.h, references and acknowledgments where relevant to my code in the last few commits.

Please let me know if you still feel unfairly treated.

Take care!

**Comment by mikaelpatel** [comment]
Looks good. Guess there are other projects that you also could reference as inspiration for your project? Last I must say that you have used the Cosa components very nicely and put together something that may be considered to be too complex for the Arduino.

**Comment by sehlstrom** [comment]
@mikaelpatel 
I'm gad to hear.

Yes, there are some other inspirational sources for the project in general. Also some specific ideas for how to create the web page produced using a background call using ajax. Unfortunately I do not remember the source so I need to put some investigation into that in order to find it again. But it is on the todo-list.

Perhaps to complex, but it works as intended in general. The only flaw is that the DeviceTimer that is supposed to be dispatched each weekday morning at 06:40 is not working. Which is strange since all other timers work as they should.

Thanks for your input on good practice!
